name: kaneo

x-networks: &default-network
  networks:
    kaneo-network:

networks:
  kaneo-network:
    name: kaneo-network
    driver: bridge

services:
  postgres:
    container_name: kaneo-postgres
    image: postgres:16-alpine
    pull_policy: always
    restart: unless-stopped
    #ports:
    #  - "5432:5432"
    volumes:
      - /mnt/user/appdata/kaneo/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kaneo -d kaneo"]
      interval: 10s
      timeout: 5s
      retries: 5
    <<: *default-network

  kaneo:
    container_name: kaneo
    build:
      context: .
      dockerfile: Dockerfile.kaneo
    image: kaneo-custom
    init: true
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5173:5173"
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1:5173/api/health",
        ]
      interval: 30s
      timeout: 5s
      start_period: 60s
      retries: 3
    <<: *default-network
